### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by ArgTang** [toolbox4minecraft/amidst#217]
Hello

I was wanting to try poking around in the code (possibly adding #205 ) but i cant seem to get it to compile. Not too familiar with external libraries, but witch and how do i add this one?

regards

![compileerror](https://cloud.githubusercontent.com/assets/8416172/17172012/7b42d1dc-53f3-11e6-821e-f539990231ab.PNG)

**Comment by stefandollase** [comment]
It has been a while since I looked into the dependencies and how each of them is installed. However, this should be resolved if you follow the steps under [Building the jar file](https://github.com/toolbox4minecraft/amidst/wiki/Building-from-Source-Code#building-the-jar-file) once.

Please let me know if this resolved it.

**Comment by ArgTang** [comment]
Solution: make sure you make new project from pom.xml. New project from existing sources won work, Regular build in IDEA will not work because of the jnbt library is not on maven central, but locally in libs folder. Maven clean command will fix this as discussed in #132.

not solved yet: running application after build

**Comment by stefandollase** [comment]
Good to hear that you figured it out.

I have no experience with IntelliJ Idea and this project is focused on the Eclipse IDE. Thus, I suggest you to use Eclipse. For example, you should use our code formatter, which only works with Eclipse.
